# filename: superset_config.py
import os

# Generate a strong secret once and keep it stable (don’t change on each restart)
# Example: paste a value generated by: openssl rand -base64 42
SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY", "pT0z7o3ZC7yqv9pYF4kQZpQ8bC1l6fV2i3mX0yM5nR8sU2aLwKfVgQ==")

# Optional hardening
SESSION_COOKIE_SECURE = True           # if you serve over HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = 3600

